---
- name: download firewall packages
  package:
    name: "{{ item }}"
  loop:
    - firewalld
    - python3-firewall
- name: start firewall
  service:
    name: firewalld
    state: started
    enabled: yes
