---
- name: create uwsgi directory
  file:
    state: directory
    path: /etc/uwsgi/vassals
    mode: 0774
    owner: root
    group: root
- name: add Emperor uwsgi ini file
  template:
    src: templates/emperor.uwsgi.ini.j2
    dest: /etc/uwsgi/emperor.uwsgi.ini
    mode: 0644
    owner: root
    group: root
- name: add uwsgi vassal
  template:
    src: "templates/app.uwsgi.ini.j2"
    dest: "/etc/uwsgi/vassals/{{ app.name }}.uwsgi.ini"
    mode: 0644
    owner: "{{ app.name }}"
    group: "{{ app.name }}"
- name: create uwsgi sockets directory
  file:
    state: directory
    path: "/run/{{ app.name }}"
    mode: 0770
    owner: "{{ app.name }}"
    group: "nginx"
