---
- import_tasks: root-configuration.yml
  tags:
    - root
  become: true
- import_tasks: python.yml
  name: build python
  tags:
    - python
  become: true
- import_tasks: selinux.yml
  become: true
  tags:
    - selinux
