---
- name: install python build dependencies
  package:
    name:
      - clang
      - geos
      - geos-devel
      - gnutls-devel
      - libffi-devel
      - libmemcached-devel
      - ncurses-devel
      - openssl-devel
      - pcre-devel
      - postgresql-devel
      - readline-devel
      - sqlite-devel
      - python3-devel
  tags:
    - build
  when: ansible_distribution == 'Fedora'

- name: fetch python tarballs
  get_url:
    url: https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz
    dest: /usr/local/src/Python-{{ python_version }}.tar.gz
    mode: 0644
    owner: root
    group: wheel
  tags:
    - build

- name: extract tarball
  unarchive:
    src: /usr/local/src/Python-{{ python_version }}.tar.gz
    dest: /usr/local/src
    remote_src: yes
  tags:
    - build

- name: configure python{{ python_version }} src with optimizations
  command:
    cmd: "{{ item }}"
    chdir: /usr/local/src/Python-{{ python_version }}
  loop:
    - "./configure --prefix=/usr/local --enable-optimizations"
    - make
    - make install
  tags:
    - build

## cleanup src code
- name: cleanup python src (1)
  file:
    path: /usr/local/src/Python-{{ python_version }}.tar.gz
    state: absent
  tags:
    - cleanup

- name: cleanup python src (2)
  file:
    path: /usr/local/src/Python-{{ python_version }}
    state: absent
  tags:
    - cleanup

- name: upgrade pip, setuptools and virtualenv
  pip:
    name: "{{ item }}"
    executable: /usr/local/bin/python{{ python_version | version_minor }}
    state: latest
  loop:
    - pip
    - setuptools
    - virtualenv
  tags:
    - build
